cmd/internal/obj: Fix generation of 32-bit large constants
ERROR: The compile step gives a "bad code" stemming from
cmd/internal/obj/pcln.go check, where it checks for stack
size. Any ideas why is it failing?

Various instructions only accept a 12-bit immediate in their instruction
encoding. This patch splits any instructions which have a larger
immediate and uses a temp register as auxillary to perform
the op.

NOTE: stack size adjustment throws an error when compiling runtime,
it appears that the max stack size is -10000 bytes (or I may be
interpreting the code in pcln.go incorrectly). However the file
mstats.go has functions which need more than 10000 bytes of stack
leading to "compile: bad code" error.

This probably needs to be investigated before this patch will be ready.

Change-Id: I83ad7af8ee64cfc2aea7617d8147c1597205d598